Add deletion
RedisAI/hnswlib pull request #3
Opened 2021-08-01 20:33 UTC by alonre24

This PR introduces the implementation of our new deletion algorithm for hnsw index.

It includes:
- Refactor of hnswalg.h - removing irrelevant functions, adding documentation, making code more readable.
- Add a build argument "ENABLE_PARALLELISATION", that enables synchronisation in the code for parallel indexing / searching (as hnsw supported before). Note that adding a new element to the index along with searching is not supported, and that removing (or updating data) of an element cannot be done in parallel with any other operation.
- Change example test to receive argument via command line, and to perform arbitrary deletion after every 10 insert operation. Also, print time and memory stats whenever index size is a power of 10.
- Add python bindings for the bruteforce algorithm as well, to allow measuring recall when using python API.

2021-08-02 09:27 UTC, DvirDukhan requested changes
also add `update` function please

2021-08-02 09:27 UTC, DvirDukhan commented on hnswlib/hnswalg.h
> +        // used for synchronization only when parallel indexing / searching is enabled.
`#ifdef PRALLEL_HNSW`

2021-08-02 09:27 UTC, DvirDukhan commented on hnswlib/hnswalg.h
> +                link_list_locks_(max_elements), element_levels_(max_elements) {
add `link_list_locks` to `IFDEF PARALLEL_HNSW`

2021-08-02 09:27 UTC, DvirDukhan commented on hnswlib/hnswalg.h
> -            revSize_ = 1.0 / mult_;
deleted since not in use

2021-08-02 09:27 UTC, DvirDukhan commented on hnswlib/hnswalg.h
> +            size_links_level0_ = maxM0_ * sizeof(tableint) + sizeof(linklistsizeint)
reorder according to the documenation

2021-08-02 09:27 UTC, DvirDukhan commented on hnswlib/hnswalg.h
> -            free(data_level0_memory_);
restore this delete

2021-08-02 09:27 UTC, DvirDukhan commented on hnswlib/hnswalg.h
> +        linklistsizeint *get_linklist0(tableint internal_id, char *data_level0_memory_) const {
remove

2021-08-02 09:27 UTC, DvirDukhan commented on hnswlib/hnswalg.h
> +        CandidatesQueue<dist_t> searchBaseLayer(tableint ep_id, const void *data_point, int layer) {
merge with seatchBaseLayer

2021-08-02 09:27 UTC, DvirDukhan commented on hnswlib/hnswalg.h
> +            label_c = label_lookup_[label];
this is another retrival of the data that you got in line 561

2021-08-02 09:27 UTC, DvirDukhan commented on hnswlib/hnswalg.h
> +            while (orig_candidates.size() > 0) {
try to put duplicated code in a function

2021-08-02 13:40 UTC, alonre24 commented on hnswlib/hnswalg.h
> -            revSize_ = 1.0 / mult_;
**only `revSize`**

2021-08-04 11:39 UTC, DvirDukhan approved these changes

2021-08-04 14:16 UTC, merged